// terme (lowercase, no accents) → expansion appended to the FTS query as OR alternatives.
// Tuned by eval/cases.json (recall@5). Keep expansions short: FTS5 phrase syntax.
export const SYNONYMES: Record<string, string> = {
  rh: "ressources humaines",
  drh: "ressources humaines",
  dev: "developpeur",
  developpeuse: "developpeur",
  informatique: "numerique",
  it: "informatique",
  cyber: "cybersecurite",
  cybersecu: "cybersecurite",
  data: "donnees",
  ia: "intelligence artificielle",
  ai: "intelligence artificielle",
  bts: "brevet de technicien superieur",
  dut: "diplome universitaire de technologie",
  but: "bachelor universitaire de technologie",
  cap: "certificat d'aptitude professionnelle",
  bac: "baccalaureat",
  bp: "brevet professionnel",
  cqp: "certificat de qualification professionnelle",
  mco: "management commercial operationnel",
  ndrc: "negociation digitalisation relation client",
  sio: "services informatiques aux organisations",
  gpme: "gestion de la pme",
  sam: "support action manageriale",
  cg: "comptabilite gestion",
  fpa: "formateur professionnel adultes",
  cda: "concepteur developpeur applications",
  dwwm: "developpeur web mobile",
  tssr: "technicien superieur systemes reseaux",
  tp: "titre professionnel",
  compta: "comptabilite",
  comptable: "comptabilite",
  gestionnaire: "gestion",
  marketing: "mercatique",
  commercial: "commerce vente",
  vendeur: "vente",
  manager: "management",
  infirmier: "infirmiere soins infirmiers",
  infirmiere: "infirmier soins infirmiers",
  cuisinier: "cuisine",
  patissier: "patisserie",
  boulanger: "boulangerie",
  coiffeur: "coiffure",
  esthetique: "estheticienne",
  electricien: "electricite electrotechnique",
  plombier: "plomberie",
  soudeur: "soudage",
  mecanicien: "mecanique maintenance",
  chauffeur: "conducteur transport routier",
  logistique: "supply chain",
  batiment: "btp construction",
  btp: "batiment travaux publics",
  immo: "immobilier",
  paie: "paye",
  assistante: "assistant",
  bureautique: "office",
  anglais: "langue anglaise toeic",
  formateur: "formation professionnelle adultes",
  cariste: "caces chariot",
  caces: "conduite en securite chariots",
  drone: "telepilote",
  photovoltaique: "solaire",
  agricole: "agriculture",
  web: "developpeur web",
  reseaux: "reseau systemes",
  sysadmin: "administrateur systemes reseaux",
  devops: "administrateur systemes cloud",
  ux: "designer",
  ui: "designer",
  graphiste: "design graphique",
  concepteur: "developpeur",
  qhse: "qualite securite environnement",
  hse: "hygiene securite environnement",
  ssiap: "securite incendie",
  sst: "sauveteur secouriste du travail",
};
